// This file is autogenerated by the Studio.
// Don't modify this file directly.
import {type TailwindColor} from "tailwindcss/tailwind-config";
declare module "tailwindcss/tailwind-config" {
  // We need to extend the TailwindColor type to include our custom colors.
  // This is a bit of a hack, but it's the only way to get the types to work.
  type CustomColors =
    | "background"
    | "foreground"
    | "card"
    | "card-foreground"
    | "popover"
    | "popover-foreground"
    | "primary"
    | "primary-foreground"
    | "secondary"
    | "secondary-foreground"
    | "muted"
    | "muted-foreground"
    | "accent"
    | "accent-foreground"
    | "destructive"
    | "destructive-foreground"
    | "border"
    | "input"
    | "ring"
    | "trail"
    | "chart-1"
    | "chart-2"
    | "chart-3"
    | "chart-4"
    | "chart-5"
    | "sidebar"
    | "sidebar-foreground"
    | "sidebar-primary"
    | "sidebar-primary-foreground"
    | "sidebar-accent"
    | "sidebar-accent-foreground"
    | "sidebar-border"
    | "sidebar-ring";
  type TailwindColor = TailwindColor | CustomColors;
}
